name: flutter_iot_cake_fast_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
 
environment:
  sdk: ">=3.2.0 <4.0.0"
 
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2 # ใช้สำหรับแสดงแผนที่
  font_awesome_flutter: ^10.12.0  # ใช้งานไอคอนจากเว็บ FontAwesome.com
  google_fonts: ^8.0.1 # ใช้งานฟอนต์จาก fonts.google.com
  carousel_slider: ^5.1.2  # ใช้สำหรับสร้าง Slider  
  latlong2: ^0.9.1 # ใช้สำหรับจัดการพิกัดบนแผนที่
  url_launcher: ^6.3.2 # ใช้สำหรับเปิดลิงก์ภายนอก เช่น เปิดแผนที่ในแอป เปิดเบราว์เซอร์ หรือโทรศัพท์
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.3
 
flutter:
  uses-material-design: true
  assets:
    - assets/images/
 
icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true